### ISSUE TITLE
请问一下，我看到Fling是这样的

### ISSUE THREAD

**Issue by LLQQHH** [wuyr/ArcSlidingHelper#1]
float offset = fixAngle(Math.abs(y - mLastScrollOffset));
mSlidingListener.onSliding(isClockwiseScrolling ? offset : -offset);
为什么offset变成了角度，这不是一个距离差吗

**Comment by wuyr** [comment]
是的，这个是手指松开后的惯性滚动处理。
之所以这样做，
1. 是因为条件不足：
在进行惯性滚动时，只能从Scroller中取得新的x,y轴坐标值（两个点），如果要像处理ACTION_MOVE那样计算的话，那么还差一个点(旋转点)的坐标才能计算，如果直接使用原来的旋转点，肯定是不行的，因为惯性是直线运动，也就是无论运动距离有多长，都是无法计算出我们想要的角度的，就像这张图一样：
![preview](https://github.com/wuyr/ArcSlidingHelper/raw/master/previews/issues-1.png)

2. 当手指松开后，肉眼几乎计算不了精准的旋转角度，这种情况完全可以把惯性的偏移量当做旋转的角度。

**另外：**
ArcSlidingHelper已提供 **setScrollAvailabilityRatio(float ratio)** 方法，可以借助此方法来调整惯性移动的速度。谢谢~

**Comment by LLQQHH** [comment]
知道了，谢谢您，还专门画了图解答，请问一下，您的画图软件是什么，还有突然发现您的ArcSLidinghelper的csdn链接挂了！

**Comment by wuyr** [comment]
我是用QQ的截图工具直接画的，哈哈
这是CSDN的bug（想哭），我昨晚编辑了一下那篇文章并点了保存，结果今天发现变成了草稿。。。。想哭，时间也自动更新到了昨晚的编辑时间
上一次也是这一篇文章，本来是18年6月份发布的，结果上一次却更新到了19年1月，而且文章数量还+1了，本来就只有12篇的，现在却变成了13篇，本来这篇文章是排在FanLayout之前的，结果却排在了第一，无语死了。。。我不知道我等下如果再点发布文章的话，会不会文章数还+1，害的大家还以为我又发布了新的文章（想哭）

**Comment by LLQQHH** [comment]
哈哈，知道了，您发的自定义都很好，都让我们知其所以然！希望您能发更多的文章！

**Comment by wuyr** [comment]
哈哈，谢谢~ 我会坚持更新的，共勉！
